import type { LeagueChampionKnowledgeProfile } from "./types";

export const ksanteCombatProfile = {
  profileQuality: "draft",
  masteryDifficulty: "very_high",
  abilities: { Q: "Ntofo Strikes", W: "Path Maker", E: "Footwork", R: "All Out" },
  archetype: ["tank skirmisher", "displacement", "peel", "duelist transformation"],
  primaryWinCondition: ["Use tank form to absorb and control space, then use (R) only when isolating a target creates a winning duel or decisive displacement."],
  dangerAbilities: ["(Q3) knockback", "(W) displacement", "(R) isolation"],
  dangerProfile: { dangerousWhen: ["(Q3) is ready.", "(W) can interrupt or push enemies.", "(R) can carry a target through terrain or isolate them."], mustRespect: ["His threat depends on ability sequencing.", "All Out changes him from tank to duelist.", "Terrain heavily changes (R) danger."] },
  commonWeaknesses: ["High execution requirement.", "Can lose durability after (R).", "Punishable when key displacement spells are down."],
  damageType: "physical",
  hardCrowdControl: ["(Q3) knockback", "(W) knockback", "(R) displacement"],
  id: "KSante",
  importantAbilityNotes: ["(Q) stacks toward a displacement cast.", "(W) charges damage reduction and displacement.", "(E) dashes and shields allies if targeted.", "(R) isolates a target and changes his stats."],
  lanePlan: { avoids: ["Using (R) into a losing duel.", "Trading without (Q) stacks or (W).", "Burning (E) where he cannot exit."], idealLaneState: "A controlled top lane where KSante farms safely, stacks (Q), and threatens displacement near terrain.", wants: ["Terrain angles.", "Short trades around (Q) stacks.", "Teamfights where he can peel before choosing an (R) target."] },
  laneIdentity: { earlyGameAgency: "medium", lanePressure: "medium", preferredGameState: ["Controlled melee lanes.", "Front-line peel fights.", "Terrain fights where displacement matters."], scalingPriority: "medium", winLaneBy: ["Managing (Q) stacks.", "Denying enemy commits with (W).", "Using (R) to isolate the right target."] },
  majorPowerSpikes: ["Level 6 (R).", "First tank item.", "Teamfights around terrain."],
  matchupPreferences: { strongInto: ["Melee champions he can control.", "Carries vulnerable to isolation.", "Teams that engage into his peel."], weakInto: ["Ranged poke.", "Sustained duelists after he uses (R).", "Champions that avoid terrain angles."] },
  mobilityLevel: "medium",
  name: "K'Sante",
  offMetaRoles: [],
  powerSpikes: { major: [{ timing: "Level 6", reason: "(R) unlocks isolation and All Out dueling", changesGameplay: "KSante can turn terrain into a kill angle or peel play.", playerAction: "Use (R) only when the isolated fight is favorable.", enemyResponse: "Avoid terrain angles and punish his lower durability after (R)." }, { timing: "First tank item", reason: "Base durability makes his control pattern safer", changesGameplay: "He can front line while looking for displacement.", playerAction: "Trade around (Q) stacks and preserve (W) for key damage.", enemyResponse: "Force cooldowns before committing." }] },
  primaryRoles: ["top"],
  primaryTradingPattern: "Stack (Q), use (W) and (E) to control short trades, and reserve (R) for isolated fights that he actually wins.",
  punishProfile: { canPunish: ["Enemies near terrain.", "Targets hit by (Q3).", "Divers committing into his peel."], strugglesToPunish: ["Ranged champions.", "Duelists who beat All Out."] },
  secondaryRoles: [],
  shields: ["(E) shield"],
  softCrowdControl: ["(Q) slow"],
  stealthOrInvisibility: null,
  strategicIdentity: { laneGoal: "control", preferredGameLength: "medium", scalingProfile: "mid", winMethod: ["front-line control", "target isolation", "terrain displacement"] },
  sustain: [],
  trading: { badTradeConditions: ["(Q) stacks are unavailable.", "(W) is down.", "(R) isolates a stronger duelist."], goodTradeConditions: ["(Q3) is ready.", "Terrain creates (R) threat.", "Enemy burst can be absorbed by (W)."], primaryPattern: "Control space first, trade around stacked (Q), and transform with (R) only for a verified isolation payoff." },
  punishWindows: ["After (W), his damage reduction and displacement are down.", "After (R), he is less tanky.", "Without (Q3), his forced engage is weaker."],
} satisfies LeagueChampionKnowledgeProfile;

