import type { LeagueChampionKnowledgeProfile } from "./types";

export const singedCombatProfile = {
  profileQuality: "draft",
  masteryDifficulty: "high",
  abilities: { Q: "Poison Trail", W: "Mega Adhesive", E: "Fling", R: "Insanity Potion" },
  archetype: ["proxy", "disruptor", "damage-over-time", "teamfight chaos"],
  primaryWinCondition: ["Disrupt normal lane patterns with wave control or proxy pressure, then use speed and (E) to drag enemies through poison and bad positions."],
  dangerAbilities: ["(E) fling", "(W) grounding slow", "(R) speed and durability"],
  dangerProfile: { dangerousWhen: ["Enemies chase through (Q).", "(W) prevents dashes before (E).", "(R) lets him run through fights and survive."], mustRespect: ["Chasing Singed is often the trap.", "He wins by breaking normal lane rules.", "Grounding changes mobility matchups heavily."] },
  commonWeaknesses: ["Low direct burst.", "Can be punished if proxy paths are collapsed on.", "Struggles when enemies clear waves safely and refuse chase."],
  damageType: "magic",
  hardCrowdControl: ["(E) displacement"],
  id: "Singed",
  importantAbilityNotes: ["(Q) leaves poison behind him.", "(W) slows and grounds.", "(E) flips a target behind him.", "(R) grants combat stats and speed."],
  lanePlan: { avoids: ["Taking fair stationary duels.", "Proxying without tracking enemy movement.", "Using (E) when it flings enemies to safety."], idealLaneState: "A warped top lane where Singed controls waves, forces bad chases, and makes enemies choose between farm loss and awkward rotations.", wants: ["Enemies chasing through poison.", "Wave states he can proxy or crash.", "Fights where he can disrupt carries."] },
  laneIdentity: { earlyGameAgency: "medium", lanePressure: "medium", preferredGameState: ["Proxy or wave disruption.", "Chaotic skirmishes.", "Teamfights where he zones carries by running through them."], scalingPriority: "medium", winLaneBy: ["Forcing bad chases.", "Breaking wave tempo.", "Using (W) plus (E) to punish mobility."] },
  majorPowerSpikes: ["Level 6 (R).", "First AP bruiser/tank item.", "Mid-game movement and durability."],
  matchupPreferences: { strongInto: ["Champions that chase him.", "Low waveclear lanes.", "Mobility champions punished by grounding."], weakInto: ["Ranged waveclear.", "Coordinated collapses on proxy.", "Champions that ignore chase bait."] },
  mobilityLevel: "medium",
  name: "Singed",
  offMetaRoles: [],
  powerSpikes: { major: [{ timing: "Level 6", reason: "(R) adds speed and durability", changesGameplay: "Singed can survive deeper paths and longer disruption fights.", playerAction: "Use (R) to force bad rotations or teamfight disruption.", enemyResponse: "Do not chase through poison; cut off exits instead." }, { timing: "First AP bruiser or tank item", reason: "Durability lets him keep poison active longer", changesGameplay: "He can absorb more pressure while disrupting waves.", playerAction: "Pressure waves and force enemies into inefficient responses.", enemyResponse: "Clear waves and collapse with numbers." }] },
  primaryRoles: ["top"],
  primaryTradingPattern: "Avoid fair front-facing trades; make enemies walk through (Q), ground them with (W), and fling them into bad spacing with (E).",
  punishProfile: { canPunish: ["Enemies chasing through poison.", "Dash champions caught by (W).", "Targets flung into his team or tower."], strugglesToPunish: ["Ranged champions who clear and disengage.", "Teams that refuse chase bait."] },
  secondaryRoles: [],
  shields: [],
  softCrowdControl: ["(W) slow and grounding"],
  stealthOrInvisibility: null,
  strategicIdentity: { laneGoal: "control", preferredGameLength: "medium", scalingProfile: "mid", winMethod: ["wave disruption", "proxy pressure", "teamfight chaos"] },
  sustain: [],
  trading: { badTradeConditions: ["He is forced into stationary duels.", "(R) is down before deep pressure.", "Enemies can collapse his route."], goodTradeConditions: ["Enemies chase through (Q).", "(W) can ground mobility.", "Wave state makes proxy pressure valuable."], primaryPattern: "Win by movement, poison uptime, and positional disruption rather than direct dueling." },
  punishWindows: ["When (R) is down, deep pressure is riskier.", "If proxy paths are tracked, he can be collapsed on.", "When enemies clear waves and refuse chase, his pressure drops."],
} satisfies LeagueChampionKnowledgeProfile;
