import type { LeagueChampionKnowledgeProfile } from "./types";

export const sionCombatProfile = {
  profileQuality: "draft",
  masteryDifficulty: "medium",
  abilities: { Q: "Decimating Smash", W: "Soul Furnace", E: "Roar of the Slayer", R: "Unstoppable Onslaught" },
  archetype: ["tank", "scaling health", "engage", "wave control"],
  primaryWinCondition: ["Use wave control and health scaling to become a durable front line, then start or disrupt fights with charged (Q) and (R)."],
  dangerAbilities: ["Charged (Q) knockup", "(R) engage", "(E) slow"],
  dangerProfile: { dangerousWhen: ["(Q) can charge from fog or after slow.", "(R) has a clear engage path.", "He has enough health scaling to ignore short trades."], mustRespect: ["Fog-of-war (Q) is much stronger than visible charge.", "(R) can start fights from long range.", "Even passive can punish sloppy low-health fights."] },
  commonWeaknesses: ["Very telegraphed when visible.", "Low mobility without (R).", "Can be kited or punished during missed (Q)."],
  damageType: "physical",
  hardCrowdControl: ["(Q) knockup", "(R) knockup"],
  id: "Sion",
  importantAbilityNotes: ["(Q) is stronger when charged.", "(W) gives shield and permanent health scaling from kills.", "(E) slows and reduces armor.", "(R) is long-range unstoppable engage."],
  lanePlan: { avoids: ["Charging (Q) in obvious spots.", "Using (R) with no follow-up path.", "Taking repeated % health damage trades."], idealLaneState: "A controlled lane where Sion can farm, stack health with (W), and threaten charged (Q) from brush or wave control.", wants: ["Brush or fog angles.", "Waveclear into scaling.", "Teamfight engage paths."] },
  laneIdentity: { earlyGameAgency: "low", lanePressure: "medium", preferredGameState: ["Stable farm lanes.", "Front-to-back teamfights.", "Long engage paths with (R)."], scalingPriority: "high", winLaneBy: ["Using waveclear to survive.", "Landing charged (Q).", "Stacking health and forcing teamfight utility."] },
  majorPowerSpikes: ["Level 6 (R).", "First tank item.", "High health scaling."],
  matchupPreferences: { strongInto: ["Low pressure tanks.", "Teams vulnerable to long engage.", "Lanes where waveclear prevents dives."], weakInto: ["Percent-health damage.", "Mobile champions that dodge (Q).", "Sustained duelists in side lane." ] },
  mobilityLevel: "low",
  name: "Sion",
  offMetaRoles: [],
  powerSpikes: { major: [{ timing: "Level 6", reason: "(R) unlocks long-range engage", changesGameplay: "Sion can force fights or return to lane with pressure.", playerAction: "Use (R) with clear pathing and team follow-up.", enemyResponse: "Sidestep or break the engage angle before impact." }, { timing: "High health scaling", reason: "(W) stacks and tank items make him hard to remove", changesGameplay: "He becomes a reliable front line.", playerAction: "Absorb space and threaten charged (Q) zones.", enemyResponse: "Use % health damage and avoid fog Q angles." }] },
  primaryRoles: ["top"],
  primaryTradingPattern: "Use (E) to slow, charge (Q) from protected angles, and rely on (W) shield plus scaling rather than chasing mobile enemies.",
  punishProfile: { canPunish: ["Enemies walking into charged (Q).", "Targets lined up for (R).", "Low mobility champions near brush."], strugglesToPunish: ["Mobile duelists.", "Champions that punish visible (Q)."] },
  secondaryRoles: [],
  shields: ["(W) shield"],
  softCrowdControl: ["(E) slow"],
  stealthOrInvisibility: null,
  strategicIdentity: { laneGoal: "teamfight", preferredGameLength: "long", scalingProfile: "late", winMethod: ["health scaling", "front-line engage", "wave control"] },
  sustain: [],
  trading: { badTradeConditions: ["(Q) is interrupted or dodged.", "(W) shield is down.", "The enemy has sustained % health damage."], goodTradeConditions: ["(E) slow sets up (Q).", "Fog hides his charge.", "(R) has a clean path."], primaryPattern: "Control waves, hide charged (Q) angles, and scale into front-line engage." },
  punishWindows: ["After missed (Q), his threat drops.", "When (W) shield is down, trades stick more.", "Without (R), he lacks reliable long engage."],
} satisfies LeagueChampionKnowledgeProfile;

