import type { LeagueChampionKnowledgeProfile } from "./types";

export const trundleCombatProfile = {
  profileQuality: "draft",
  masteryDifficulty: "low",
  abilities: { Q: "Chomp", W: "Frozen Domain", E: "Pillar of Ice", R: "Subjugate" },
  archetype: ["juggernaut", "anti-tank", "splitpush", "stat steal"],
  primaryWinCondition: ["Force extended duels with (Q) and (W), use (E) to trap or disrupt movement, and punish tanks with (R) stat drain."],
  dangerAbilities: ["(E) pillar", "(R) stat drain", "(Q) attack damage steal"],
  dangerProfile: { dangerousWhen: ["He fights inside (W).", "(E) blocks escape or interrupts movement.", "(R) targets a durable champion and steals their resistances."], mustRespect: ["He is strongest in long, direct fights.", "Tanks lose much of their durability into (R).", "Pillar can create gank or chase angles."] },
  commonWeaknesses: ["Low mobility outside (W).", "Limited burst.", "Can be kited or disengaged before extended fights develop."],
  damageType: "physical",
  hardCrowdControl: [],
  id: "Trundle",
  importantAbilityNotes: ["(Q) steals attack damage.", "(W) improves movement, attack speed, and healing in the zone.", "(E) creates terrain and slows.", "(R) drains health and resistances."],
  lanePlan: { avoids: ["Fighting outside (W) when the enemy can kite.", "Using (E) without a chase or disengage purpose.", "Ulting low-value targets instead of durable champions."], idealLaneState: "A long top lane where Trundle can force extended trades, pillar escape paths, and pressure towers after winning duels.", wants: ["Melee opponents who must fight him.", "Tanks vulnerable to (R).", "Side-lane space for splitpush."] },
  laneIdentity: { earlyGameAgency: "medium", lanePressure: "medium", preferredGameState: ["Extended melee duels.", "Splitpush side lanes.", "Anti-tank front-line fights."], scalingPriority: "medium", winLaneBy: ["Trading inside (W).", "Pillaring escape paths.", "Using (R) on tanks or bruisers."] },
  majorPowerSpikes: ["Level 6 (R).", "First dueling item.", "Side-lane tower pressure."],
  matchupPreferences: { strongInto: ["Tanks and stat-check melees.", "Low mobility side-laners.", "Teams relying on a durable front line."], weakInto: ["Ranged kiting.", "Disengage that denies long fights.", "Burst that avoids extended trades."] },
  mobilityLevel: "low",
  name: "Trundle",
  offMetaRoles: [],
  powerSpikes: { major: [{ timing: "Level 6", reason: "(R) steals health and resistances", changesGameplay: "Durable enemies become much easier for Trundle to duel.", playerAction: "Use (R) on the highest-value tanky target before committing.", enemyResponse: "Avoid fighting him during (R) and kite out its value." }, { timing: "First dueling item", reason: "Extended side-lane fights become stronger", changesGameplay: "He can pressure towers and punish isolated defenders.", playerAction: "Force side-lane trades inside (W).", enemyResponse: "Do not take long isolated fights." }] },
  primaryRoles: ["jungle", "top"],
  primaryTradingPattern: "Use (Q) to weaken the enemy's damage, fight inside (W), and place (E) to deny escape or protect disengage.",
  punishProfile: { canPunish: ["Tanks during (R).", "Enemies trapped by (E).", "Melee champions forced into long trades."], strugglesToPunish: ["Ranged champions.", "Teams that disengage his (W) zone."] },
  secondaryRoles: [],
  shields: [],
  softCrowdControl: ["(E) slow"],
  stealthOrInvisibility: null,
  strategicIdentity: { laneGoal: "splitpush", preferredGameLength: "medium", scalingProfile: "mid", winMethod: ["extended duels", "anti-tank stat steal", "side-lane tower pressure"] },
  sustain: ["(W) amplifies healing", "(R) health drain"],
  trading: { badTradeConditions: ["Outside (W).", "(E) is wasted.", "(R) is unavailable into tanks."], goodTradeConditions: ["The enemy must fight in (W).", "(E) cuts off escape.", "(R) can drain a durable target."], primaryPattern: "Turn fights into long stat checks, then use pillar and Subjugate to make disengage or tanking fail." },
  punishWindows: ["When (W) is down, his chase and sustain drop.", "After (E), he has less control.", "If (R) is spent on a low-value target, tanks can front line more safely."],
} satisfies LeagueChampionKnowledgeProfile;

