import type { LeagueChampionKnowledgeProfile } from "./types";

export const urgotCombatProfile = {
  profileQuality: "draft",
  masteryDifficulty: "medium",
  abilities: { Q: "Corrosive Charge", W: "Purge", E: "Disdain", R: "Fear Beyond Death" },
  archetype: ["ranged juggernaut", "execute", "side-lane", "anti-engage"],
  primaryWinCondition: ["Use ranged poke and shotgun knees to control melee space, punish commits with (E), and convert health leads into (R) execute pressure."],
  dangerAbilities: ["(E) flip and shield", "(R) execute", "Passive shotgun legs"],
  dangerProfile: { dangerousWhen: ["(E) flips a target into his damage.", "Passive legs are available around the target.", "(R) hits a low-health champion and creates execute fear."], mustRespect: ["His ranged juggernaut spacing is unusual for top lane.", "The execute changes low-health all-ins.", "(E) can punish champions who think they are engaging first."] },
  commonWeaknesses: ["Low mobility.", "Can be kited after (E).", "Needs correct spacing to use passive legs efficiently."],
  damageType: "physical",
  hardCrowdControl: ["(E) flip", "(R) fear on execute"],
  id: "Urgot",
  importantAbilityNotes: ["Passive legs fire around his body.", "(W) locks onto marked targets.", "(E) shields and flips if it hits.", "(R) executes below threshold if recast connects."],
  lanePlan: { avoids: ["Using (E) into a losing all-in.", "Fighting with passive legs on cooldown.", "Missing (R) and losing execute pressure."], idealLaneState: "A controlled top lane where Urgot pokes from range, keeps enough space to rotate passive legs, and threatens (E) against engage.", wants: ["Enemies walking into (E).", "Side-lane duels after items.", "Low-health targets for (R)."] },
  laneIdentity: { earlyGameAgency: "medium", lanePressure: "medium", preferredGameState: ["Controlled ranged-melee spacing.", "Side-lane duels.", "Front-line fights where execute fear can spread."], scalingPriority: "high", winLaneBy: ["Rotating passive legs.", "Flipping engage with (E).", "Landing (R) execute."] },
  majorPowerSpikes: ["Level 6 (R).", "Level 9 (W) uptime pattern.", "First bruiser item."],
  matchupPreferences: { strongInto: ["Melee champions that commit into (E).", "Side-lane fights.", "Low mobility targets vulnerable to execute."], weakInto: ["Long-range poke.", "Mobile champions that dodge (E) and (R).", "Champions that kite his short range."] },
  mobilityLevel: "low",
  name: "Urgot",
  offMetaRoles: [],
  powerSpikes: { major: [{ timing: "Level 6", reason: "(R) unlocks execute threat", changesGameplay: "Low-health trades become dangerous even if Urgot cannot finish with autos.", playerAction: "Use poke and passive legs to set execute range before firing (R).", enemyResponse: "Avoid staying low and dodge the execute projectile." }, { timing: "Level 9", reason: "(W) uptime makes sustained damage smoother", changesGameplay: "Side-lane duels become more consistent.", playerAction: "Pressure longer fights when passive legs are available.", enemyResponse: "Kite and punish after (E) misses." }] },
  primaryRoles: ["top"],
  primaryTradingPattern: "Poke with range, rotate passive legs for damage, and hold (E) to punish enemy engage before threatening (R) execute.",
  punishProfile: { canPunish: ["Enemies engaging into (E).", "Targets near execute range.", "Melee champions who cannot avoid passive legs."], strugglesToPunish: ["Long-range poke.", "Mobile champions that dodge skillshots."] },
  secondaryRoles: [],
  shields: ["(E) shield"],
  softCrowdControl: ["(Q) slow"],
  stealthOrInvisibility: null,
  strategicIdentity: { laneGoal: "scale", preferredGameLength: "medium", scalingProfile: "mid", winMethod: ["ranged juggernaut trades", "side-lane duels", "execute pressure"] },
  sustain: [],
  trading: { badTradeConditions: ["(E) misses.", "Passive legs are unavailable.", "(R) is down near kill thresholds."], goodTradeConditions: ["The enemy commits into (E).", "Passive legs can rotate.", "The target is near (R) range."], primaryPattern: "Control spacing until the opponent commits, flip them with (E), then use passive legs and (R) to finish." },
  punishWindows: ["After (E), he is easier to kite.", "If (R) misses, execute pressure disappears.", "When passive legs are on cooldown, damage is lower."],
} satisfies LeagueChampionKnowledgeProfile;

