import type { LeagueChampionKnowledgeProfile } from "./types";

export const vayneCombatProfile = {
  profileQuality: "draft",
  masteryDifficulty: "high",
  abilities: { Q: "Tumble", W: "Silver Bolts", E: "Condemn", R: "Final Hour" },
  archetype: ["marksman", "anti-tank", "scaling duelist", "ranged top"],
  primaryWinCondition: ["Use ranged spacing and (Q) repositioning to deny melee champions, then scale into side-lane duels and anti-tank DPS through (W)."],
  dangerAbilities: ["(E) wall stun", "(W) true damage", "(R) stealth tumble"],
  dangerProfile: { dangerousWhen: ["She has room to kite.", "(E) can pin a target into terrain.", "(R) is active and (Q) gives stealth repositioning."], mustRespect: ["Her true damage punishes tanks.", "Ranged top pressure can deny farm early.", "She is fragile if engage reaches her."] },
  commonWeaknesses: ["Very fragile.", "Low waveclear.", "Can be punished by ganks and hard engage."],
  damageType: "physical",
  hardCrowdControl: ["(E) wall stun"],
  id: "Vayne",
  importantAbilityNotes: ["(Q) repositions and empowers the next attack.", "(W) deals true damage every third hit.", "(E) knocks back and stuns into terrain.", "(R) empowers combat and grants stealth during (Q)."],
  lanePlan: { avoids: ["Pushing without vision.", "Using (Q) forward when engage is ready.", "Fighting near walls that help the enemy if she cannot control spacing."], idealLaneState: "A ranged top lane where Vayne keeps the wave safe, pokes melee champions, and holds (E) for all-ins.", wants: ["Space to kite.", "Tanks or bruisers she can shred.", "Side-lane duels after items."] },
  laneIdentity: { earlyGameAgency: "high", lanePressure: "high", preferredGameState: ["Ranged denial lanes.", "Side-lane duels with space.", "Late fights where she can free-hit front line."], scalingPriority: "high", winLaneBy: ["Spacing with autos and (Q).", "Condemning engage into walls.", "Scaling into true damage DPS."] },
  majorPowerSpikes: ["Level 6 (R).", "First marksman item.", "Two-item side-lane duel spike."],
  matchupPreferences: { strongInto: ["Tanks and low mobility bruisers.", "Champions she can kite.", "Frontlines vulnerable to true damage."], weakInto: ["Hard engage.", "Gank pressure.", "Waveclear and poke that traps her under tower."] },
  mobilityLevel: "high",
  name: "Vayne",
  offMetaRoles: [],
  powerSpikes: { major: [{ timing: "Level 6", reason: "(R) empowers dueling and stealth repositioning", changesGameplay: "Vayne can outplay committed melee all-ins with stealth tumbles.", playerAction: "Use (R) when there is enough space to kite.", enemyResponse: "Force her into short spaces or engage after (E)." }, { timing: "Two-item side-lane spike", reason: "True damage DPS becomes a major duel threat", changesGameplay: "Tanks and bruisers struggle to answer her alone.", playerAction: "Pressure side lane with vision and kite space.", enemyResponse: "Collapse with numbers rather than isolated duels." }] },
  primaryRoles: ["adc", "top"],
  primaryTradingPattern: "Auto from max range, use (Q) to maintain spacing, and hold (E) for enemy engage or terrain stun rather than poke.",
  punishProfile: { canPunish: ["Tanks in extended range.", "Melee champions without gap close.", "Targets near walls for (E)."], strugglesToPunish: ["Coordinated ganks.", "Hard engage after (E)."] },
  secondaryRoles: [],
  shields: [],
  softCrowdControl: [],
  stealthOrInvisibility: "(R) makes (Q) briefly stealth Vayne.",
  strategicIdentity: { laneGoal: "scale", preferredGameLength: "long", scalingProfile: "late", winMethod: ["ranged top pressure", "anti-tank DPS", "side-lane kiting"] },
  sustain: [],
  trading: { badTradeConditions: ["(Q) is used forward into engage.", "(E) is down.", "The wave is pushed without vision."], goodTradeConditions: ["There is space to kite.", "The enemy's engage is down.", "A wall angle enables (E)."], primaryPattern: "Win with spacing discipline and true damage, not by standing still in fair melee range." },
  punishWindows: ["After (E), engage is more reliable.", "If she pushes without vision, ganks punish hard.", "Low waveclear can trap her in bad lane states."],
} satisfies LeagueChampionKnowledgeProfile;

