import type { GameEvent } from "@/src/features/events/types";

const seedTimestamp = "2026-05-18T00:00:00.000Z";

export const events: GameEvent[] = [
  {
    id: "diablo-4-season-13-start",
    gameId: "diablo-4",
    seasonId: "diablo-4-season-13-active",
    title: "Diablo IV Season 13 starts",
    description: "New seasonal powers, questline updates, and reward track.",
    type: "season-start",
    startDate: "2026-05-01",
    sourceUrl: "https://diablo4.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-season-13-midseason-patch",
    gameId: "diablo-4",
    seasonId: "diablo-4-season-13-active",
    title: "Season 13 midseason update",
    description: "Balance changes and event rewards refresh.",
    type: "patch",
    startDate: "2026-06-18",
    sourceUrl: "https://diablo4.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-mothers-blessing",
    gameId: "diablo-4",
    seasonId: "diablo-4-season-13-active",
    title: "Mother's Blessing weekend",
    description: "Bonus experience and gold for seasonal characters.",
    type: "event",
    startDate: "2026-06-28",
    endDate: "2026-07-01",
    sourceUrl: "https://diablo4.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-season-13-end",
    gameId: "diablo-4",
    seasonId: "diablo-4-season-13-active",
    title: "Season 13 ends",
    description: "Seasonal progression moves into the eternal realm.",
    type: "season-end",
    startDate: "2026-07-14",
    sourceUrl: "https://diablo4.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-season-4-start",
    gameId: "world-of-warcraft",
    seasonId: "wow-season-4",
    title: "World of Warcraft Season 4 starts",
    description: "Mythic+, raid rotation, and PvP season rewards open.",
    type: "season-start",
    startDate: "2026-06-01",
    sourceUrl: "https://worldofwarcraft.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-class-tuning",
    gameId: "world-of-warcraft",
    seasonId: "wow-season-4",
    title: "Class tuning update",
    description: "Dungeon, raid, and specialization balance adjustments.",
    type: "patch",
    startDate: "2026-06-11",
    sourceUrl: "https://worldofwarcraft.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-timewalking-week",
    gameId: "world-of-warcraft",
    seasonId: "wow-season-4",
    title: "Timewalking bonus event",
    description: "Weekly event with bonus rewards and dungeon rotation.",
    type: "event",
    startDate: "2026-06-23",
    endDate: "2026-06-30",
    sourceUrl: "https://worldofwarcraft.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-season-4-end",
    gameId: "world-of-warcraft",
    seasonId: "wow-season-4",
    title: "Season 4 ends",
    description: "Seasonal achievements and rewards lock in.",
    type: "season-end",
    startDate: "2026-08-15",
    sourceUrl: "https://worldofwarcraft.blizzard.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-season-16-start",
    gameId: "league-of-legends",
    seasonId: "league-of-legends-season-16",
    title: "League of Legends Season 16 starts",
    description: "Ranked split opens with placement matches and rewards.",
    type: "season-start",
    startDate: "2026-06-01",
    sourceUrl: "https://www.leagueoflegends.com/news",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-patch-16-12",
    gameId: "league-of-legends",
    seasonId: "league-of-legends-season-16",
    title: "Patch 16.12",
    description: "Champion balance, item changes, and ranked fixes.",
    type: "patch",
    startDate: "2026-06-12",
    sourceUrl: "https://www.leagueoflegends.com/news/tags/patch-notes",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-clash-cup",
    gameId: "league-of-legends",
    seasonId: "league-of-legends-season-16",
    title: "Clash cup weekend",
    description: "Team tournament weekend with bracket rewards.",
    type: "event",
    startDate: "2026-06-27",
    endDate: "2026-06-29",
    sourceUrl: "https://www.leagueoflegends.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-season-16-end",
    gameId: "league-of-legends",
    seasonId: "league-of-legends-season-16",
    title: "Season 16 split ends",
    description: "Ranked split rewards and ladder standings finalize.",
    type: "season-end",
    startDate: "2026-08-15",
    sourceUrl: "https://www.leagueoflegends.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-season-4-start",
    gameId: "last-epoch",
    seasonId: "last-epoch-season-4-upcoming",
    title: "Last Epoch Season 4 starts",
    description: "New cycle ladder, endgame updates, and item changes.",
    type: "season-start",
    startDate: "2026-06-01",
    sourceUrl: "https://forum.lastepoch.com",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-cycle-4-hotfix",
    gameId: "last-epoch",
    seasonId: "last-epoch-season-4-upcoming",
    title: "Cycle 4 hotfix window",
    description: "Stability fixes and early cycle balance adjustments.",
    type: "patch",
    startDate: "2026-06-07",
    sourceUrl: "https://forum.lastepoch.com",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-gold-boost",
    gameId: "last-epoch",
    seasonId: "last-epoch-season-4-upcoming",
    title: "Echo rush weekend",
    description: "Bonus monolith rewards and increased echo variety.",
    type: "event",
    startDate: "2026-06-21",
    endDate: "2026-06-24",
    sourceUrl: "https://forum.lastepoch.com",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-season-4-end",
    gameId: "last-epoch",
    seasonId: "last-epoch-season-4-ending-soon",
    title: "Last Epoch Season 4 ends",
    description: "Cycle ladder closes and characters move to legacy.",
    type: "season-end",
    startDate: "2026-07-28",
    sourceUrl: "https://forum.lastepoch.com",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-season-21-start",
    gameId: "path-of-exile",
    seasonId: "path-of-exile-season-21",
    title: "Path of Exile Season 21 starts",
    description: "Challenge league launches with economy reset.",
    type: "season-start",
    startDate: "2026-06-01",
    sourceUrl: "https://www.pathofexile.com/news",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-league-hotfix",
    gameId: "path-of-exile",
    seasonId: "path-of-exile-season-21",
    title: "League launch hotfix",
    description: "Bug fixes, reward tuning, and economy adjustments.",
    type: "patch",
    startDate: "2026-06-06",
    sourceUrl: "https://www.pathofexile.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-race-weekend",
    gameId: "path-of-exile",
    seasonId: "path-of-exile-season-21",
    title: "Race weekend",
    description: "Community ladder event with fresh-start rules.",
    type: "event",
    startDate: "2026-06-20",
    endDate: "2026-06-22",
    sourceUrl: "https://www.pathofexile.com/news",
    isOfficial: false,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-season-21-end",
    gameId: "path-of-exile",
    seasonId: "path-of-exile-season-21",
    title: "Season 21 ends",
    description: "Challenge league migration and reward distribution.",
    type: "season-end",
    startDate: "2026-08-15",
    sourceUrl: "https://www.pathofexile.com/news",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
