import type { ResourceGroup } from "@/src/features/resource-groups/types";

const seedTimestamp = "2026-05-18T00:00:00.000Z";

export const resourceGroups: ResourceGroup[] = [
  {
    id: "diablo-4-build-prep",
    gameId: "diablo-4",
    title: "Build prep",
    description: "Leveling, endgame, and planner resources.",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["d4-maxroll-builds", "d4-icy-veins-guides", "d4-mobalytics-builds"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-official-tools",
    gameId: "diablo-4",
    title: "Official and tools",
    description: "Patch notes and community utility links.",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["d4-official-patch-notes", "d4-trade"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-guides",
    gameId: "world-of-warcraft",
    title: "Class and dungeon guides",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["wow-wowhead", "wow-icy-veins", "wow-raider-io"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-progression",
    gameId: "world-of-warcraft",
    title: "Progression tracking",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["wow-warcraft-logs", "wow-official-news"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-ranked-prep",
    gameId: "league-of-legends",
    title: "Ranked prep",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["lol-ugg-builds", "lol-opgg-stats", "lol-lolalytics"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-tools",
    gameId: "league-of-legends",
    title: "Meta and patch tools",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["lol-mobalytics", "lol-official-patch-notes"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-build-prep",
    gameId: "last-epoch",
    title: "Cycle prep",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["last-epoch-maxroll", "last-epoch-icy-veins", "last-epoch-tools"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-official-tools",
    gameId: "last-epoch",
    title: "Official and calculators",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["last-epoch-official-forums", "last-epoch-tunklab"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-league-prep",
    gameId: "path-of-exile",
    title: "League prep",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["poe-official-news", "poe-maxroll", "poe-wiki"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-tools",
    gameId: "path-of-exile",
    title: "Economy and filters",
    isFeatured: true,
    isVerified: true,
    resourceIds: ["poe-ninja", "poe-filterblade"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
