import type { Creator, GameCreator } from "@/src/features/creators/types";

const seedTimestamp = "2026-05-18T00:00:00.000Z";

export const creators: Creator[] = [
  {
    id: "blizzard-entertainment",
    name: "Blizzard Entertainment",
    type: "studio",
    websiteUrl: "https://www.blizzard.com",
    sourceUrl: "https://www.blizzard.com",
    avatarColor: "#4f46e5",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "riot-games",
    name: "Riot Games",
    type: "studio",
    websiteUrl: "https://www.riotgames.com",
    sourceUrl: "https://www.riotgames.com",
    avatarColor: "#dc2626",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "eleventh-hour-games",
    name: "Eleventh Hour Games",
    type: "studio",
    websiteUrl: "https://eleventhhour.games",
    sourceUrl: "https://eleventhhour.games",
    avatarColor: "#2563eb",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "grinding-gear-games",
    name: "Grinding Gear Games",
    type: "studio",
    websiteUrl: "https://www.grindinggear.com",
    sourceUrl: "https://www.grindinggear.com",
    avatarColor: "#b45309",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "maxroll",
    name: "Maxroll",
    type: "guide-site",
    websiteUrl: "https://maxroll.gg",
    sourceUrl: "https://maxroll.gg",
    avatarColor: "#0284c7",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "icy-veins",
    name: "Icy Veins",
    type: "guide-site",
    websiteUrl: "https://www.icy-veins.com",
    sourceUrl: "https://www.icy-veins.com",
    avatarColor: "#7c3aed",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "mobalytics",
    name: "Mobalytics",
    type: "tool-provider",
    websiteUrl: "https://mobalytics.gg",
    sourceUrl: "https://mobalytics.gg",
    avatarColor: "#8b5cf6",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wowhead",
    name: "Wowhead",
    type: "guide-site",
    websiteUrl: "https://www.wowhead.com",
    sourceUrl: "https://www.wowhead.com",
    avatarColor: "#f97316",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "raider-io",
    name: "Raider.IO",
    type: "tool-provider",
    websiteUrl: "https://raider.io",
    sourceUrl: "https://raider.io",
    avatarColor: "#0ea5e9",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "warcraft-logs",
    name: "Warcraft Logs",
    type: "tool-provider",
    websiteUrl: "https://www.warcraftlogs.com",
    sourceUrl: "https://www.warcraftlogs.com",
    avatarColor: "#ef4444",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "u-gg",
    name: "U.GG",
    type: "tool-provider",
    websiteUrl: "https://u.gg",
    sourceUrl: "https://u.gg",
    avatarColor: "#22c55e",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "op-gg",
    name: "OP.GG",
    type: "tool-provider",
    websiteUrl: "https://www.op.gg",
    sourceUrl: "https://www.op.gg",
    avatarColor: "#38bdf8",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lolalytics",
    name: "LoLalytics",
    type: "tool-provider",
    websiteUrl: "https://lolalytics.com",
    sourceUrl: "https://lolalytics.com",
    avatarColor: "#eab308",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-tools",
    name: "Last Epoch Tools",
    type: "tool-provider",
    websiteUrl: "https://www.lastepochtools.com",
    sourceUrl: "https://www.lastepochtools.com",
    avatarColor: "#14b8a6",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "tunklab",
    name: "Tunklab",
    type: "tool-provider",
    websiteUrl: "https://lastepoch.tunklab.com",
    sourceUrl: "https://lastepoch.tunklab.com",
    avatarColor: "#64748b",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-wiki",
    name: "PoE Wiki",
    type: "community",
    websiteUrl: "https://www.poewiki.net",
    sourceUrl: "https://www.poewiki.net",
    avatarColor: "#a855f7",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-ninja",
    name: "poe.ninja",
    type: "tool-provider",
    websiteUrl: "https://poe.ninja",
    sourceUrl: "https://poe.ninja",
    avatarColor: "#f59e0b",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "filterblade",
    name: "FilterBlade",
    type: "tool-provider",
    websiteUrl: "https://www.filterblade.xyz",
    sourceUrl: "https://www.filterblade.xyz",
    avatarColor: "#10b981",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const gameCreators: GameCreator[] = [
  {
    id: "diablo-4-blizzard",
    gameId: "diablo-4",
    creatorId: "blizzard-entertainment",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-maxroll",
    gameId: "diablo-4",
    creatorId: "maxroll",
    role: "guide-creator",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-icy-veins",
    gameId: "diablo-4",
    creatorId: "icy-veins",
    role: "guide-creator",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-mobalytics",
    gameId: "diablo-4",
    creatorId: "mobalytics",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-blizzard",
    gameId: "world-of-warcraft",
    creatorId: "blizzard-entertainment",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-wowhead",
    gameId: "world-of-warcraft",
    creatorId: "wowhead",
    role: "guide-creator",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-icy-veins",
    gameId: "world-of-warcraft",
    creatorId: "icy-veins",
    role: "guide-creator",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-raider-io",
    gameId: "world-of-warcraft",
    creatorId: "raider-io",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-warcraft-logs",
    gameId: "world-of-warcraft",
    creatorId: "warcraft-logs",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-riot",
    gameId: "league-of-legends",
    creatorId: "riot-games",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-u-gg",
    gameId: "league-of-legends",
    creatorId: "u-gg",
    role: "tooling",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-op-gg",
    gameId: "league-of-legends",
    creatorId: "op-gg",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-mobalytics",
    gameId: "league-of-legends",
    creatorId: "mobalytics",
    role: "guide-creator",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-lolalytics",
    gameId: "league-of-legends",
    creatorId: "lolalytics",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-eleventh-hour",
    gameId: "last-epoch",
    creatorId: "eleventh-hour-games",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-maxroll",
    gameId: "last-epoch",
    creatorId: "maxroll",
    role: "guide-creator",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-tools-link",
    gameId: "last-epoch",
    creatorId: "last-epoch-tools",
    role: "tooling",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-icy-veins",
    gameId: "last-epoch",
    creatorId: "icy-veins",
    role: "guide-creator",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-tunklab",
    gameId: "last-epoch",
    creatorId: "tunklab",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-grinding-gear",
    gameId: "path-of-exile",
    creatorId: "grinding-gear-games",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-maxroll",
    gameId: "path-of-exile",
    creatorId: "maxroll",
    role: "guide-creator",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-poe-wiki",
    gameId: "path-of-exile",
    creatorId: "poe-wiki",
    role: "community",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-poe-ninja",
    gameId: "path-of-exile",
    creatorId: "poe-ninja",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-filterblade",
    gameId: "path-of-exile",
    creatorId: "filterblade",
    role: "tooling",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
