import type { Creator, GameCreator } from "@/src/features/creators/types";

const seedTimestamp = "2026-05-18T00:00:00.000Z";

export const creators: Creator[] = [
  {
    id: "blizzard-entertainment",
    name: "Blizzard Entertainment",
    type: "studio",
    websiteUrl: "https://www.blizzard.com",
    sourceUrl: "https://www.blizzard.com",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "riot-games",
    name: "Riot Games",
    type: "studio",
    websiteUrl: "https://www.riotgames.com",
    sourceUrl: "https://www.riotgames.com",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "eleventh-hour-games",
    name: "Eleventh Hour Games",
    type: "studio",
    websiteUrl: "https://eleventhhour.games",
    sourceUrl: "https://eleventhhour.games",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "grinding-gear-games",
    name: "Grinding Gear Games",
    type: "studio",
    websiteUrl: "https://www.grindinggear.com",
    sourceUrl: "https://www.grindinggear.com",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];

export const gameCreators: GameCreator[] = [
  {
    id: "diablo-4-blizzard",
    gameId: "diablo-4",
    creatorId: "blizzard-entertainment",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "world-of-warcraft-blizzard",
    gameId: "world-of-warcraft",
    creatorId: "blizzard-entertainment",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "league-of-legends-riot",
    gameId: "league-of-legends",
    creatorId: "riot-games",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-eleventh-hour",
    gameId: "last-epoch",
    creatorId: "eleventh-hour-games",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-grinding-gear",
    gameId: "path-of-exile",
    creatorId: "grinding-gear-games",
    role: "developer-publisher",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
