import type { Resource } from "@/src/features/resources/types";

const seedTimestamp = "2026-05-16T00:00:00.000Z";

export const resources: Resource[] = [
  {
    id: "d4-maxroll-builds",
    gameId: "diablo-4",
    label: "Maxroll Builds",
    description: "Leveling and endgame build guides",
    url: "https://maxroll.gg/d4",
    category: "builds",
    featured: true,
    isFeatured: true,
    isVerified: true,
    sourceUrl: "https://maxroll.gg/d4",
    tags: ["builds", "leveling"],
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "d4-icy-veins-guides",
    gameId: "diablo-4",
    label: "Icy Veins Guides",
    description: "Class guides and seasonal explainers",
    url: "https://www.icy-veins.com/d4/",
    category: "builds",
    isVerified: true,
    sourceUrl: "https://www.icy-veins.com/d4/",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "d4-mobalytics-builds",
    gameId: "diablo-4",
    label: "Mobalytics Builds",
    description: "Build planner and meta snapshots",
    url: "https://mobalytics.gg/diablo-4",
    category: "tools",
    isVerified: true,
    sourceUrl: "https://mobalytics.gg/diablo-4",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "d4-official-patch-notes",
    gameId: "diablo-4",
    label: "Official Patch Notes",
    description: "Blizzard news and seasonal updates",
    url: "https://diablo4.blizzard.com/news",
    category: "patch-notes",
    featured: true,
    isFeatured: true,
    isOfficial: true,
    isVerified: true,
    sourceUrl: "https://diablo4.blizzard.com/news",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "d4-trade",
    gameId: "diablo-4",
    label: "Diablo.trade",
    description: "Community trade marketplace",
    url: "https://diablo.trade",
    category: "trade",
    isVerified: true,
    sourceUrl: "https://diablo.trade",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-wowhead",
    gameId: "world-of-warcraft",
    label: "Wowhead",
    description: "Database, guides, and news",
    url: "https://www.wowhead.com",
    category: "wiki",
    featured: true,
    isFeatured: true,
    isVerified: true,
    sourceUrl: "https://www.wowhead.com",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-icy-veins",
    gameId: "world-of-warcraft",
    label: "Icy Veins WoW",
    description: "Class builds and season guides",
    url: "https://www.icy-veins.com/wow/",
    category: "builds",
    isVerified: true,
    sourceUrl: "https://www.icy-veins.com/wow/",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-raider-io",
    gameId: "world-of-warcraft",
    label: "Raider.IO",
    description: "Mythic+ rankings and routes",
    url: "https://raider.io",
    category: "stats",
    isVerified: true,
    sourceUrl: "https://raider.io",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-warcraft-logs",
    gameId: "world-of-warcraft",
    label: "Warcraft Logs",
    description: "Raid and dungeon performance logs",
    url: "https://www.warcraftlogs.com",
    category: "stats",
    isVerified: true,
    sourceUrl: "https://www.warcraftlogs.com",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-official-news",
    gameId: "world-of-warcraft",
    label: "Official News",
    description: "Blizzard announcements and patch notes",
    url: "https://worldofwarcraft.blizzard.com/news",
    category: "patch-notes",
    isOfficial: true,
    isVerified: true,
    sourceUrl: "https://worldofwarcraft.blizzard.com/news",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-ugg-builds",
    gameId: "league-of-legends",
    label: "U.GG Builds",
    description: "Champion builds and matchup data",
    url: "https://u.gg/lol/champions",
    category: "builds",
    featured: true,
    isFeatured: true,
    isVerified: true,
    sourceUrl: "https://u.gg/lol/champions",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-opgg-stats",
    gameId: "league-of-legends",
    label: "OP.GG",
    description: "Ranked stats and match history",
    url: "https://www.op.gg",
    category: "stats",
    isVerified: true,
    sourceUrl: "https://www.op.gg",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-mobalytics",
    gameId: "league-of-legends",
    label: "Mobalytics LoL",
    description: "Builds, tier lists, and coaching tools",
    url: "https://mobalytics.gg/lol",
    category: "tools",
    isVerified: true,
    sourceUrl: "https://mobalytics.gg/lol",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-lolalytics",
    gameId: "league-of-legends",
    label: "LoLalytics",
    description: "Champion statistics and tier lists",
    url: "https://lolalytics.com",
    category: "tier-list",
    isVerified: true,
    sourceUrl: "https://lolalytics.com",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-official-patch-notes",
    gameId: "league-of-legends",
    label: "Official Patch Notes",
    description: "Riot patch notes and season updates",
    url: "https://www.leagueoflegends.com/news/tags/patch-notes",
    category: "patch-notes",
    isOfficial: true,
    isVerified: true,
    sourceUrl: "https://www.leagueoflegends.com/news/tags/patch-notes",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-maxroll",
    gameId: "last-epoch",
    label: "Maxroll Last Epoch",
    description: "Leveling, endgame, and farming guides",
    url: "https://maxroll.gg/last-epoch",
    category: "builds",
    featured: true,
    isFeatured: true,
    isVerified: true,
    sourceUrl: "https://maxroll.gg/last-epoch",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-tools",
    gameId: "last-epoch",
    label: "Last Epoch Tools",
    description: "Database, planner, and item lookup",
    url: "https://www.lastepochtools.com",
    category: "tools",
    isVerified: true,
    sourceUrl: "https://www.lastepochtools.com",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-icy-veins",
    gameId: "last-epoch",
    label: "Icy Veins Last Epoch",
    description: "Build guides and class explainers",
    url: "https://www.icy-veins.com/last-epoch/",
    category: "builds",
    isVerified: true,
    sourceUrl: "https://www.icy-veins.com/last-epoch/",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-official-forums",
    gameId: "last-epoch",
    label: "Official Forums",
    description: "Patch notes and developer updates",
    url: "https://forum.lastepoch.com",
    category: "patch-notes",
    isOfficial: true,
    isVerified: true,
    sourceUrl: "https://forum.lastepoch.com",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-tunklab",
    gameId: "last-epoch",
    label: "Tunklab",
    description: "Community calculators and tools",
    url: "https://lastepoch.tunklab.com",
    category: "tools",
    isVerified: true,
    sourceUrl: "https://lastepoch.tunklab.com",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-official-news",
    gameId: "path-of-exile",
    label: "Official News",
    description: "League announcements and patch notes",
    url: "https://www.pathofexile.com/news",
    category: "patch-notes",
    featured: true,
    isFeatured: true,
    isOfficial: true,
    isVerified: true,
    sourceUrl: "https://www.pathofexile.com/news",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-maxroll",
    gameId: "path-of-exile",
    label: "Maxroll PoE",
    description: "League starters and endgame builds",
    url: "https://maxroll.gg/poe",
    category: "builds",
    isVerified: true,
    sourceUrl: "https://maxroll.gg/poe",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-wiki",
    gameId: "path-of-exile",
    label: "PoE Wiki",
    description: "Community-maintained mechanics wiki",
    url: "https://www.poewiki.net",
    category: "wiki",
    isVerified: true,
    sourceUrl: "https://www.poewiki.net",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-ninja",
    gameId: "path-of-exile",
    label: "poe.ninja",
    description: "Economy, builds, and ladder data",
    url: "https://poe.ninja",
    category: "stats",
    isVerified: true,
    sourceUrl: "https://poe.ninja",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "poe-filterblade",
    gameId: "path-of-exile",
    label: "FilterBlade",
    description: "Loot filter editor and presets",
    url: "https://www.filterblade.xyz",
    category: "tools",
    isVerified: true,
    sourceUrl: "https://www.filterblade.xyz",
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
