import type { LeagueChampion } from "./champions";
import type { LeagueRole } from "./roles";

const championRolesByRole = {
  adc: [
    "Aphelios",
    "Ashe",
    "Caitlyn",
    "Draven",
    "Ezreal",
    "Jhin",
    "Jinx",
    "Kaisa",
    "Kalista",
    "KogMaw",
    "Lucian",
    "MissFortune",
    "Nilah",
    "Samira",
    "Sivir",
    "Smolder",
    "Tristana",
    "Twitch",
    "Varus",
    "Vayne",
    "Xayah",
    "Zeri",
  ],
  jungle: [
    "Amumu",
    "Belveth",
    "Briar",
    "Diana",
    "Ekko",
    "Elise",
    "Evelynn",
    "Fiddlesticks",
    "Gragas",
    "Graves",
    "Hecarim",
    "Ivern",
    "JarvanIV",
    "Karthus",
    "Kayn",
    "Khazix",
    "Kindred",
    "LeeSin",
    "Lillia",
    "MasterYi",
    "MonkeyKing",
    "Nidalee",
    "Nocturne",
    "Nunu",
    "Poppy",
    "Rammus",
    "RekSai",
    "Rengar",
    "Sejuani",
    "Shaco",
    "Shyvana",
    "Skarner",
    "Taliyah",
    "Trundle",
    "Udyr",
    "Vi",
    "Viego",
    "Volibear",
    "Warwick",
    "XinZhao",
    "Zac",
  ],
  mid: [
    "Ahri",
    "Akali",
    "Akshan",
    "Anivia",
    "Annie",
    "AurelionSol",
    "Aurora",
    "Azir",
    "Cassiopeia",
    "Corki",
    "Diana",
    "Ekko",
    "Fizz",
    "Galio",
    "Hwei",
    "Irelia",
    "Kassadin",
    "Katarina",
    "Leblanc",
    "Lissandra",
    "Lux",
    "Malzahar",
    "Naafiri",
    "Neeko",
    "Orianna",
    "Qiyana",
    "Ryze",
    "Sylas",
    "Syndra",
    "Taliyah",
    "Talon",
    "TwistedFate",
    "Veigar",
    "Vex",
    "Viktor",
    "Vladimir",
    "Xerath",
    "Yasuo",
    "Yone",
    "Zed",
    "Ziggs",
    "Zoe",
  ],
  support: [
    "Alistar",
    "Bard",
    "Blitzcrank",
    "Brand",
    "Braum",
    "Janna",
    "Karma",
    "Leona",
    "Lulu",
    "Lux",
    "Maokai",
    "Milio",
    "Morgana",
    "Nami",
    "Nautilus",
    "Neeko",
    "Pyke",
    "Rakan",
    "Rell",
    "Renata",
    "Senna",
    "Seraphine",
    "Sona",
    "Soraka",
    "Swain",
    "TahmKench",
    "Taric",
    "Thresh",
    "Velkoz",
    "Xerath",
    "Yuumi",
    "Zilean",
    "Zyra",
  ],
  top: [
    "Aatrox",
    "Akali",
    "Camille",
    "Chogath",
    "Darius",
    "DrMundo",
    "Fiora",
    "Gangplank",
    "Garen",
    "Gnar",
    "Gragas",
    "Gwen",
    "Heimerdinger",
    "Illaoi",
    "Irelia",
    "Jax",
    "Jayce",
    "Kayle",
    "Kennen",
    "Kled",
    "KSante",
    "Malphite",
    "Mordekaiser",
    "Nasus",
    "Olaf",
    "Ornn",
    "Pantheon",
    "Poppy",
    "Quinn",
    "Renekton",
    "Riven",
    "Rumble",
    "Sett",
    "Shen",
    "Singed",
    "Sion",
    "TahmKench",
    "Teemo",
    "Trundle",
    "Tryndamere",
    "Urgot",
    "Vayne",
    "Vladimir",
    "Volibear",
    "Warwick",
    "Yasuo",
    "Yone",
    "Yorick",
  ],
} satisfies Record<LeagueRole, readonly string[]>;

const championRolesById = new Map<string, LeagueRole[]>();

for (const [role, championIds] of Object.entries(championRolesByRole) as Array<
  [LeagueRole, readonly string[]]
>) {
  for (const championId of championIds) {
    championRolesById.set(championId, [
      ...(championRolesById.get(championId) ?? []),
      role,
    ]);
  }
}

export function getChampionRoles(champion: Pick<LeagueChampion, "id">) {
  return championRolesById.get(champion.id) ?? [];
}

export function isChampionInRole(
  champion: Pick<LeagueChampion, "id">,
  role: LeagueRole
) {
  return getChampionRoles(champion).includes(role);
}
