import type { CommunityLink } from "@/src/features/community-links/types";

const seedTimestamp = "2026-05-18T00:00:00.000Z";

export const communityLinks: CommunityLink[] = [
  {
    id: "diablo-4-forums",
    gameId: "diablo-4",
    label: "Official Forums",
    type: "forum",
    url: "https://us.forums.blizzard.com/en/d4",
    sourceUrl: "https://us.forums.blizzard.com/en/d4",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-reddit",
    gameId: "diablo-4",
    label: "Diablo IV Reddit",
    type: "reddit",
    url: "https://www.reddit.com/r/diablo4",
    sourceUrl: "https://www.reddit.com/r/diablo4",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-forums",
    gameId: "world-of-warcraft",
    label: "Official Forums",
    type: "forum",
    url: "https://us.forums.blizzard.com/en/wow",
    sourceUrl: "https://us.forums.blizzard.com/en/wow",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-discord",
    gameId: "league-of-legends",
    label: "League of Legends Discord",
    type: "discord",
    url: "https://discord.com/invite/leagueoflegends",
    sourceUrl: "https://discord.com/invite/leagueoflegends",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-discord",
    gameId: "last-epoch",
    label: "Last Epoch Discord",
    type: "discord",
    url: "https://discord.com/invite/lastepoch",
    sourceUrl: "https://discord.com/invite/lastepoch",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-forums",
    gameId: "path-of-exile",
    label: "Official Forums",
    type: "forum",
    url: "https://www.pathofexile.com/forum",
    sourceUrl: "https://www.pathofexile.com/forum",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
