import type { CommunityLink } from "@/src/features/community-links/types";

const seedTimestamp = "2026-05-18T00:00:00.000Z";

export const communityLinks: CommunityLink[] = [
  {
    id: "diablo-4-official-forums",
    gameId: "diablo-4",
    label: "Official Forums",
    type: "forum",
    url: "https://us.forums.blizzard.com/en/d4",
    sourceUrl: "https://us.forums.blizzard.com/en/d4",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-reddit",
    gameId: "diablo-4",
    label: "Diablo IV Reddit",
    type: "reddit",
    url: "https://www.reddit.com/r/diablo4",
    sourceUrl: "https://www.reddit.com/r/diablo4",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "diablo-4-youtube",
    gameId: "diablo-4",
    label: "Diablo YouTube",
    type: "video",
    url: "https://www.youtube.com/@Diablo",
    sourceUrl: "https://www.youtube.com/@Diablo",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-official-forums",
    gameId: "world-of-warcraft",
    label: "Official Forums",
    type: "forum",
    url: "https://us.forums.blizzard.com/en/wow",
    sourceUrl: "https://us.forums.blizzard.com/en/wow",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-reddit",
    gameId: "world-of-warcraft",
    label: "World of Warcraft Reddit",
    type: "reddit",
    url: "https://www.reddit.com/r/wow",
    sourceUrl: "https://www.reddit.com/r/wow",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "wow-youtube",
    gameId: "world-of-warcraft",
    label: "Warcraft YouTube",
    type: "video",
    url: "https://www.youtube.com/@Warcraft",
    sourceUrl: "https://www.youtube.com/@Warcraft",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-discord",
    gameId: "league-of-legends",
    label: "League of Legends Discord",
    type: "discord",
    url: "https://discord.com/invite/leagueoflegends",
    sourceUrl: "https://discord.com/invite/leagueoflegends",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-reddit",
    gameId: "league-of-legends",
    label: "League of Legends Reddit",
    type: "reddit",
    url: "https://www.reddit.com/r/leagueoflegends",
    sourceUrl: "https://www.reddit.com/r/leagueoflegends",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "lol-youtube",
    gameId: "league-of-legends",
    label: "League YouTube",
    type: "video",
    url: "https://www.youtube.com/@leagueoflegends",
    sourceUrl: "https://www.youtube.com/@leagueoflegends",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-discord",
    gameId: "last-epoch",
    label: "Last Epoch Discord",
    type: "discord",
    url: "https://discord.com/invite/lastepoch",
    sourceUrl: "https://discord.com/invite/lastepoch",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-forums",
    gameId: "last-epoch",
    label: "Official Forums",
    type: "forum",
    url: "https://forum.lastepoch.com",
    sourceUrl: "https://forum.lastepoch.com",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "last-epoch-reddit",
    gameId: "last-epoch",
    label: "Last Epoch Reddit",
    type: "reddit",
    url: "https://www.reddit.com/r/LastEpoch",
    sourceUrl: "https://www.reddit.com/r/LastEpoch",
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-forums",
    gameId: "path-of-exile",
    label: "Official Forums",
    type: "forum",
    url: "https://www.pathofexile.com/forum",
    sourceUrl: "https://www.pathofexile.com/forum",
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-reddit",
    gameId: "path-of-exile",
    label: "Path of Exile Reddit",
    type: "reddit",
    url: "https://www.reddit.com/r/pathofexile",
    sourceUrl: "https://www.reddit.com/r/pathofexile",
    isVerified: true,
    isFeatured: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: "path-of-exile-youtube",
    gameId: "path-of-exile",
    label: "Path of Exile YouTube",
    type: "video",
    url: "https://www.youtube.com/@grindinggear",
    sourceUrl: "https://www.youtube.com/@grindinggear",
    isOfficial: true,
    isVerified: true,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
