create table if not exists public.riot_collection_jobs (
  id bigint generated by default as identity primary key,
  status text not null default 'queued',
  platform text not null default 'EUW1',
  regional_route text not null default 'EUROPE',
  queue_type text not null default 'RANKED_SOLO_5x5',
  rank_bracket text not null,
  role text not null,
  focus_champion_id text references public.league_champions(id) on update cascade on delete set null,
  target_unique_matches integer not null,
  automatic_seed_discovery boolean not null default true,
  current_patch_only boolean not null default true,
  resolved_patch text,
  unique_matches_processed integer not null default 0,
  new_matchup_observations integer not null default 0,
  duplicate_match_ids integer not null default 0,
  stat_rows_updated integer not null default 0,
  seeds_discovered integer not null default 0,
  seeds_used integer not null default 0,
  scan_batches_started integer not null default 0,
  scan_batches_completed integer not null default 0,
  api_requests_used integer not null default 0,
  error_count integer not null default 0,
  warning_count integer not null default 0,
  stop_reason text,
  progress jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  failed_at timestamptz,
  cancelled_at timestamptz,
  updated_at timestamptz not null default now(),

  constraint riot_collection_jobs_status_check check (
    status in (
      'queued',
      'discovering-seeds',
      'selecting-seeds',
      'scanning',
      'aggregating',
      'completed',
      'completed-partial',
      'failed',
      'cancelled',
      'paused'
    )
  ),
  constraint riot_collection_jobs_rank_bracket_check check (
    rank_bracket in ('iron-silver', 'gold-emerald', 'diamond', 'master-plus')
  ),
  constraint riot_collection_jobs_role_check check (
    role in ('top', 'jungle', 'mid', 'adc', 'support', 'any')
  ),
  constraint riot_collection_jobs_target_check check (
    target_unique_matches in (50, 100, 200)
  )
);

alter table public.riot_scan_jobs
add column if not exists collection_job_id bigint references public.riot_collection_jobs(id) on delete set null;

create table if not exists public.riot_collection_job_matches (
  id bigint generated by default as identity primary key,
  collection_job_id bigint not null references public.riot_collection_jobs(id) on delete cascade,
  match_id text not null,
  role text not null,
  counted_toward_target boolean not null default true,
  observation_id uuid references public.riot_matchup_observations(id) on delete set null,
  source_scan_job_id bigint references public.riot_scan_jobs(id) on delete set null,
  duplicate_within_collection boolean not null default false,
  created_at timestamptz not null default now(),

  constraint riot_collection_job_matches_role_check check (
    role in ('top', 'jungle', 'mid', 'adc', 'support')
  ),
  constraint riot_collection_job_matches_unique unique (
    collection_job_id,
    match_id,
    role
  )
);

create table if not exists public.riot_collection_job_seeds (
  id bigint generated by default as identity primary key,
  collection_job_id bigint not null references public.riot_collection_jobs(id) on delete cascade,
  candidate_id uuid not null references public.riot_seed_candidates(id) on delete cascade,
  puuid text not null,
  source text not null default 'selected',
  source_scan_job_id bigint references public.riot_scan_jobs(id) on delete set null,
  reserved_at timestamptz not null default now(),
  released_at timestamptz,
  created_at timestamptz not null default now(),

  constraint riot_collection_job_seeds_source_check check (
    source in ('selected', 'discovered')
  ),
  constraint riot_collection_job_seeds_unique unique (
    collection_job_id,
    candidate_id
  )
);

create table if not exists public.riot_ladder_discovery_cursors (
  id bigint generated by default as identity primary key,
  platform text not null,
  queue_type text not null,
  tier text not null,
  division text not null default '',
  next_page integer not null default 1,
  last_page_fetched integer,
  last_discovered_at timestamptz,
  entries_returned integer not null default 0,
  candidates_created integer not null default 0,
  candidates_reused integer not null default 0,
  empty_page_count integer not null default 0,
  cooldown_until timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint riot_ladder_discovery_cursors_unique unique (
    platform,
    queue_type,
    tier,
    division
  ),
  constraint riot_ladder_discovery_cursors_next_page_check check (next_page >= 1)
);

create table if not exists public.riot_summoner_puuid_cache (
  id bigint generated by default as identity primary key,
  platform text not null,
  encrypted_summoner_id text not null,
  puuid text,
  lookup_status text not null default 'resolved',
  lookup_failures integer not null default 0,
  next_retry_at timestamptz,
  last_error_code text,
  last_attempted_at timestamptz not null default now(),
  last_success_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint riot_summoner_puuid_cache_status_check check (
    lookup_status in ('resolved', 'not_found', 'rate_limited', 'failed')
  ),
  constraint riot_summoner_puuid_cache_unique unique (
    platform,
    encrypted_summoner_id
  )
);

create index if not exists riot_scan_jobs_collection_job_id_idx
on public.riot_scan_jobs (collection_job_id);

create index if not exists riot_collection_jobs_created_at_idx
on public.riot_collection_jobs (created_at desc);

create index if not exists riot_collection_jobs_status_idx
on public.riot_collection_jobs (status);

create index if not exists riot_collection_job_matches_job_idx
on public.riot_collection_job_matches (collection_job_id, counted_toward_target);

create index if not exists riot_collection_job_seeds_job_idx
on public.riot_collection_job_seeds (collection_job_id);

grant select, insert, update, delete on table public.riot_collection_jobs to authenticated;
grant select, insert, update, delete on table public.riot_collection_jobs to service_role;
grant select, insert, update, delete on table public.riot_collection_job_matches to authenticated;
grant select, insert, update, delete on table public.riot_collection_job_matches to service_role;
grant select, insert, update, delete on table public.riot_collection_job_seeds to authenticated;
grant select, insert, update, delete on table public.riot_collection_job_seeds to service_role;
grant select, insert, update, delete on table public.riot_ladder_discovery_cursors to authenticated;
grant select, insert, update, delete on table public.riot_ladder_discovery_cursors to service_role;
grant select, insert, update, delete on table public.riot_summoner_puuid_cache to service_role;

alter table public.riot_collection_jobs enable row level security;
alter table public.riot_collection_job_matches enable row level security;
alter table public.riot_collection_job_seeds enable row level security;
alter table public.riot_ladder_discovery_cursors enable row level security;
alter table public.riot_summoner_puuid_cache enable row level security;

create policy "Admins can manage riot collection jobs"
on public.riot_collection_jobs
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins can manage riot collection job matches"
on public.riot_collection_job_matches
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins can manage riot collection job seeds"
on public.riot_collection_job_seeds
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Admins can manage riot ladder discovery cursors"
on public.riot_ladder_discovery_cursors
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy "Service role can manage riot collection jobs"
on public.riot_collection_jobs
for all
to service_role
using (true)
with check (true);

create policy "Service role can manage riot collection job matches"
on public.riot_collection_job_matches
for all
to service_role
using (true)
with check (true);

create policy "Service role can manage riot collection job seeds"
on public.riot_collection_job_seeds
for all
to service_role
using (true)
with check (true);

create policy "Service role can manage riot ladder discovery cursors"
on public.riot_ladder_discovery_cursors
for all
to service_role
using (true)
with check (true);

create policy "Service role can manage riot summoner puuid cache"
on public.riot_summoner_puuid_cache
for all
to service_role
using (true)
with check (true);

drop trigger if exists set_riot_collection_jobs_updated_at
on public.riot_collection_jobs;

create trigger set_riot_collection_jobs_updated_at
before update on public.riot_collection_jobs
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_riot_ladder_discovery_cursors_updated_at
on public.riot_ladder_discovery_cursors;

create trigger set_riot_ladder_discovery_cursors_updated_at
before update on public.riot_ladder_discovery_cursors
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_riot_summoner_puuid_cache_updated_at
on public.riot_summoner_puuid_cache;

create trigger set_riot_summoner_puuid_cache_updated_at
before update on public.riot_summoner_puuid_cache
for each row execute function public.set_current_timestamp_updated_at();

comment on table public.riot_collection_jobs is
  'Durable parent orchestration jobs for automated Counter Pick data collection.';

comment on table public.riot_collection_job_matches is
  'Collection-level unique match identities counted toward parent job progress.';

comment on table public.riot_collection_job_seeds is
  'Seed candidates reserved or used by a collection job to prevent reuse in the same collection.';

comment on table public.riot_ladder_discovery_cursors is
  'Ranked ladder pagination state for automated seed discovery.';

comment on table public.riot_summoner_puuid_cache is
  'Encrypted Summoner ID to PUUID lookup cache used by ladder seed discovery.';
