create table if not exists public.matchup_feedback (
  id bigint generated by default as identity primary key,
  matchup_id bigint not null references public.league_matchups(id) on update cascade on delete cascade,
  player_champion text not null,
  enemy_champion text not null,
  lane text not null,
  card_type text not null,
  feedback_type text not null,
  reason text,
  message text,
  user_id uuid references public.profiles(id) on delete set null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint matchup_feedback_lane_check check (
    lane in ('mid', 'top', 'jungle', 'adc', 'support')
  ),
  constraint matchup_feedback_type_check check (
    feedback_type in ('helpful', 'not_helpful', 'report_issue')
  ),
  constraint matchup_feedback_reason_check check (
    reason is null
    or reason in (
      'incorrect_advice',
      'missing_information',
      'too_generic',
      'wrong_champion_perspective',
      'ability_formatting_issue',
      'other'
    )
  ),
  constraint matchup_feedback_status_check check (
    status in ('open', 'reviewing', 'resolved', 'dismissed')
  )
);

create index if not exists matchup_feedback_matchup_id_idx
on public.matchup_feedback (matchup_id);

create index if not exists matchup_feedback_status_idx
on public.matchup_feedback (status);

create index if not exists matchup_feedback_lane_idx
on public.matchup_feedback (lane);

create index if not exists matchup_feedback_card_type_idx
on public.matchup_feedback (card_type);

create index if not exists matchup_feedback_reason_idx
on public.matchup_feedback (reason);

grant insert on table public.matchup_feedback to anon, authenticated;
grant select, update on table public.matchup_feedback to authenticated;
grant select, insert, update, delete on table public.matchup_feedback to service_role;

alter table public.matchup_feedback enable row level security;

drop policy if exists "Anyone can submit matchup feedback" on public.matchup_feedback;

create policy "Anyone can submit matchup feedback"
on public.matchup_feedback
for insert
to anon, authenticated
with check (
  user_id is null
  or user_id = auth.uid()
);

drop policy if exists "Admins can read matchup feedback" on public.matchup_feedback;

create policy "Admins can read matchup feedback"
on public.matchup_feedback
for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "Admins can update matchup feedback" on public.matchup_feedback;

create policy "Admins can update matchup feedback"
on public.matchup_feedback
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop trigger if exists set_matchup_feedback_updated_at on public.matchup_feedback;

create trigger set_matchup_feedback_updated_at
before update on public.matchup_feedback
for each row execute function public.set_current_timestamp_updated_at();

comment on table public.matchup_feedback is
  'User feedback on League matchup guidance cards, reviewed manually by admins.';
