create table if not exists public.riot_scan_jobs (
  id bigint generated by default as identity primary key,
  mode text not null,
  status text not null default 'queued',
  role text not null,
  seed_puuids text[] not null,
  enemy_champion text,
  counter_champion text,
  match_count integer not null default 20,
  minimum_games integer not null default 1,
  progress jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  results jsonb,
  error_message text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),

  constraint riot_scan_jobs_mode_check check (
    mode in ('target', 'discovery')
  ),
  constraint riot_scan_jobs_status_check check (
    status in ('queued', 'running', 'completed', 'failed', 'cancelled')
  ),
  constraint riot_scan_jobs_role_check check (
    role in ('top', 'jungle', 'mid', 'adc', 'support')
  ),
  constraint riot_scan_jobs_seed_puuids_check check (
    cardinality(seed_puuids) > 0
  ),
  constraint riot_scan_jobs_match_count_check check (
    match_count between 1 and 50
  ),
  constraint riot_scan_jobs_minimum_games_check check (
    minimum_games between 1 and 1000
  ),
  constraint riot_scan_jobs_target_fields_check check (
    mode <> 'target'
    or (
      enemy_champion is not null
      and counter_champion is not null
      and enemy_champion <> counter_champion
    )
  )
);

create index if not exists riot_scan_jobs_created_at_idx
on public.riot_scan_jobs (created_at desc);

create index if not exists riot_scan_jobs_status_idx
on public.riot_scan_jobs (status);

create index if not exists riot_scan_jobs_created_by_idx
on public.riot_scan_jobs (created_by);

grant select, insert, update, delete on table public.riot_scan_jobs to authenticated;
grant select, insert, update, delete on table public.riot_scan_jobs to service_role;

alter table public.riot_scan_jobs enable row level security;

drop policy if exists "Admins can manage riot scan jobs"
on public.riot_scan_jobs;

create policy "Admins can manage riot scan jobs"
on public.riot_scan_jobs
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop trigger if exists set_riot_scan_jobs_updated_at
on public.riot_scan_jobs;

create trigger set_riot_scan_jobs_updated_at
before update on public.riot_scan_jobs
for each row execute function public.set_current_timestamp_updated_at();

comment on table public.riot_scan_jobs is
  'Admin-only Riot match scanner jobs for Counter Pick research. Seed PUUIDs are stored for internal scanner use only.';
