create table if not exists public.league_counter_pick_match_statistics (
  id bigint generated by default as identity primary key,
  patch text not null,
  role text not null,
  enemy_champion_id text not null references public.league_champions(id) on update cascade on delete cascade,
  counter_champion_id text not null references public.league_champions(id) on update cascade on delete cascade,
  games integer not null default 0,
  wins integer not null default 0,
  win_rate numeric not null default 0,
  sample_confidence text not null default 'low_sample',
  last_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint league_counter_pick_match_statistics_role_check check (
    role in ('mid', 'top', 'jungle', 'adc', 'support')
  ),
  constraint league_counter_pick_match_statistics_games_check check (games >= 0),
  constraint league_counter_pick_match_statistics_wins_check check (wins >= 0 and wins <= games),
  constraint league_counter_pick_match_statistics_win_rate_check check (
    win_rate >= 0 and win_rate <= 100
  ),
  constraint league_counter_pick_match_statistics_sample_confidence_check check (
    sample_confidence in ('low_sample', 'low', 'medium', 'high')
  ),
  constraint league_counter_pick_match_statistics_unique_matchup unique (
    patch,
    role,
    enemy_champion_id,
    counter_champion_id
  ),
  constraint league_counter_pick_match_statistics_no_self_counter_check check (
    enemy_champion_id <> counter_champion_id
  )
);

create index if not exists league_counter_pick_match_statistics_enemy_role_idx
on public.league_counter_pick_match_statistics (enemy_champion_id, role);

create index if not exists league_counter_pick_match_statistics_counter_idx
on public.league_counter_pick_match_statistics (counter_champion_id);

create index if not exists league_counter_pick_match_statistics_patch_idx
on public.league_counter_pick_match_statistics (patch);

create index if not exists league_counter_pick_match_statistics_trusted_best_idx
on public.league_counter_pick_match_statistics (enemy_champion_id, role, win_rate desc, games desc)
where games >= 100;

create index if not exists league_counter_pick_match_statistics_trusted_bad_idx
on public.league_counter_pick_match_statistics (enemy_champion_id, role, win_rate asc, games desc)
where games >= 100;

grant select on table public.league_counter_pick_match_statistics to anon, authenticated;
grant select, insert, update, delete on table public.league_counter_pick_match_statistics to service_role;

alter table public.league_counter_pick_match_statistics enable row level security;

drop policy if exists "Counter pick match statistics are publicly readable"
on public.league_counter_pick_match_statistics;

create policy "Counter pick match statistics are publicly readable"
on public.league_counter_pick_match_statistics
for select
to anon, authenticated
using (true);

drop policy if exists "Service role can manage counter pick match statistics"
on public.league_counter_pick_match_statistics;

create policy "Service role can manage counter pick match statistics"
on public.league_counter_pick_match_statistics
for all
to service_role
using (true)
with check (true);

drop trigger if exists set_league_counter_pick_match_statistics_updated_at
on public.league_counter_pick_match_statistics;

create trigger set_league_counter_pick_match_statistics_updated_at
before update on public.league_counter_pick_match_statistics
for each row execute function public.set_current_timestamp_updated_at();

comment on table public.league_counter_pick_match_statistics is
  'Cached League of Legends counter-pick matchup statistics aggregated by patch, role, enemy champion, and counter champion.';
